Pipelines use new syntax for Docker images
Also modified simple so that _unit_ would pass and _integration_ would
fail. If swapped, then _unit_ would fail and _integration_ would never
run.

fixes:
```
error: invalid configuration:
unknown/extra keys:
  - jobs[0].plan[0].config.image
  - jobs[0].plan[0].config.tags
```